<?php
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

//$pdo = new PDO(); // Add your own database for example: 'mysql:host=YourDatabaseHost;port=YourPort;dbname=YourDatabaseName;...etc'

$username = $_SESSION["username"];
$survey_name = $_POST['survey_name'];
$survey_description = $_POST['survey_description'];
$questions = $_POST['question'];
$options = $_POST['option'];

$sql = "INSERT INTO surveys (username, survey_name, survey_description) VALUES (:username, :survey_name, :survey_description)";
$stmt = $pdo->prepare($sql);
$stmt->bindParam(':username', $username);
$stmt->bindParam(':survey_name', $survey_name);
$stmt->bindParam(':survey_description', $survey_description);
$stmt->execute();

// Retrieve the survey ID generated by auto-increment
$surveyId = $pdo->lastInsertId();

// Insert questions into the database
foreach ($questions as $questionIndex => $question) {
    if (empty($question)) {
        continue; // Skip this iteration and move to the next question
    }
      
    $optionValues = $options[$questionIndex];

    // Insert each question and its options into the database
    $sql = "INSERT INTO questions (survey_id, question_text, option_1, option_2, option_3, option_4, option_5) VALUES (:surveyId, :question, :option1, :option2, :option3, :option4, :option5)";
    
    $stmt = $pdo->prepare($sql);
    $stmt->bindParam(':surveyId', $surveyId);
    $stmt->bindParam(':question', $question);
    $stmt->bindParam(':option1', $optionValues[1]);
    $stmt->bindParam(':option2', $optionValues[2]);
    $stmt->bindParam(':option3', $optionValues[3]);
    $stmt->bindParam(':option4', $optionValues[4]);
    $stmt->bindParam(':option5', $optionValues[5]);
    $stmt->execute();
}

header("Location: build.php");
echo "Survey created successfully!";
?>